---
- hosts: all
  become: yes
  vars_files: 
    - "vars/{{ env }}.yml"
  roles:
    - role: mysql
      when: env == 'prod'
    - role: docker
      docker_install_compose: true
    - role: deployment
