servers=[
  {
    :hostname => "dev",
    :ip => "192.168.94.41",
    :box => "ubuntu/bionic64",
    :ram => 1024,
    :cpu => 1
  },
  {
    :hostname => "prod",
    :ip => "192.168.94.42",
    :box => "ubuntu/bionic64",
    :ram => 1024,
    :cpu => 1
  }
]

$initialize = <<-SCRIPT
cat /vagrant/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
apt-get update && apt install -y python
SCRIPT

Vagrant.configure("2") do |config|

    if Vagrant.has_plugin?("vagrant-hostmanager")
      config.hostmanager.enabled = true
      config.hostmanager.manage_guest = true
    end

    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
    end

    config.vm.provision "shell", inline: $initialize

    servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
        node.vm.box = machine[:box]
        node.vm.hostname = machine[:hostname]
        node.vm.network "private_network", ip: machine[:ip]
        node.vm.provider "virtualbox" do |vb|
            vb.memory = machine[:ram]
            vb.cpus = machine[:cpu]
            vb.linked_clone = true
        end
      end
    end
  end